site_name: Islandora Enterprise (ISLE)
site_description: Documentation for Islandora Enterprise (ISLE)

site_dir: site
docs_dir: docs
#markdown_extensions:
#    - del_ins
theme:
  name: 'material'

extra:
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'account_balance'

nav:
- Home: index.md
- 'Installation and Migration Instructions':
  - '1. Configure the Host Server':
    # - 'CentOS 7.x': '01_installation_host_server/install_on_centos.md'
    # - 'Ubuntu 18.04': '01_installation_host_server/install_on_ubuntu_1804.md'
    # - 'Docker for Mac High Sierra': '01_installation_host_server/install_docker_for_mac.md'
    # - 'Docker for Windows 10': '01_installation_host_server/install_docker_for_windows.md'
    # - 'Vagrant & VirtualBox on MacOS (Deprecated)': '01_installation_host_server/install_macos_vagrant.md'
    - 'Hardware Requirements': '01_installation_host_server/server-requirements.md'
    - 'Software Dependencies': '01_installation_host_server/software-dependencies.md'
    - 'Troubleshooting': '01_installation_host_server/install_troubleshooting.md'
  - '2. Deploy ISLE':
    - 'Deploy a Test Site':
      - 'Test Site Example User Story': '02_installation_test/ild_example_user_story.md'
      - 'Test Site Deploy Guide': '02_installation_test/ild_installation_guide.md'
      - 'Test Site Resources': '02_installation_test/ild_resources.md'
    - 'Deploy a New ISLE Site':
      - 'New Site Example User Story': '03_installation_new_site/new_site_example_user_story.md'
      - 'New Site Deploy Guide - w/ Single ISLE Environment': '03_installation_new_site/new_site_installation_guide_single.md'
      - 'New Site Deploy Guide - w/ multiple ISLE Environments': '03_installation_new_site/new_site_installation_guide_multi.md'
    - 'Migrate and Deploy an Existing Islandora site to ISLE':
      - 'Migration Example User Story': '04_installation_migration/migration_example_user_story.md'
      - 'Migration Guide': '04_installation_migration/migration_installation_guide.md'
      - 'Migration Export Checklist': '04_installation_migration/migration_export_checklist.md'
      - 'Migration Merge Checklist': '04_installation_migration/migration_merge_checklist.md'
      - 'Migration Reindex Process': '04_installation_migration/migration_reindex_process.md'
- 'Get Help': 'get_help.md'
- 'Developer Docs':
  - 'Release process': '05_developer_docs/dev_release_process.md'
  - 'Example User Story': '05_developer_docs/dev_example_user_story.md'
  - 'Testing Guide': '05_developer_docs/dev_testing_guide.md'
- 'Appendices':
  - 'Updating ISLE': '07_appendices/update_isle.md'
  - 'Editing the /ect/hosts file': '07_appendices/editing-the-hosts-file.md'
  - 'Sample IT Department Request Letter': '07_appendices/sample-it-department-request.md'
  - 'Installing a Drupal Module with Composer': '07_appendices/installing-module-with-composer.md'
  - 'Installing a Drupal Module with Drush': '07_appendices/installing-module-with-drush.md'
  - 'Opening a Terminal in a Running Container': '07_appendices/open-terminal-in-running-container.md'
  - 'Using Let''s Encrypt with ISLE' : '07_appendices/configuring-lets-encrypt.md'
  - 'Note/Warning about installing on Redhat': '07_appendices/redhat.md'
  - 'Installing on Google Cloud Platform (Google Doc)': 'https://docs.google.com/document/d/1r-I9n8mUhlJ5Z-X9AO-RrikhzH6I8bTPIL25LmtRbxE'
- 'About': 
  - 'About ISLE': '08_about/about.md'
  - 'Contributing to ISLE': '08_about/contributing_to_ISLE.md'
  - 'About Maintainers': '08_about/about_maintainers.md'
#  - 'Policies': '08_about/policies.md'
- 'Release Notes': '09_release_notes/release_notes.md'
- 'Glossary of Terms and Variables': glossary.md
